class users {

    group { "cis399":
        ensure  => present,
        gid     => 3999,
    }

        

    user { "nsato10":
        ensure  => present,
        uid     => 4000,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "nsato10",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/nsato10",
    }

    user { "mheb":
        ensure  => present,
        uid     => 4001,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "mheb",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/mheb",
    }

    user { "mister_person":
        ensure  => present,
        uid     => 4002,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "mister_person",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/mister_person",
    }
    user { "cplachno":
        ensure  => present,
        uid     => 4003,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "cplachno",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/cplachno",
    }
    user { "vino":
        ensure  => present,
        uid     => 4004,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "vino",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/vino",
    }
    user { "cnf":
        ensure  => present,
        uid     => 4005,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "cnf",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/cnf",
    }
    user { "pogrebinsky":
        ensure  => present,
        uid     => 4006,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "pogrebinsky",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/pogrebinsky",
    }
    user { "kaelas":
        ensure  => present,
        uid     => 4007,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "kaelas",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/kaelas",
    }
    user { "nboyd":
        ensure  => present,
        uid     => 4008,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "nboyd",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/nboyd",
    }
    user { "coletc":
        ensure  => present,
        uid     => 4009,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "coletc",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/coletc",
    }
    user { "jdolan":
        ensure  => present,
        uid     => 4010,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "jdolan",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/jdolan",
    }
    user { "houllette":
        ensure  => present,
        uid     => 4011,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "houllette",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/houllette",
    }
    user { "jsheabia":
        ensure  => present,
        uid     => 4012,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "jsheabia",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/jsheabia",
    }
    user { "dholstege":
        ensure  => present,
        uid     => 4013,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "dholstege",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/dholstege",
    }
    user { "jemin":
        ensure  => present,
        uid     => 4014,
        gid     => 3999,
        password => "!",
        password_max_age => "99999",
        password_min_age => "0",
        shell   => "/bin/bash",
        comment => "jemin",
        purge_ssh_keys => true,
        managehome => true,
        home    => "/home/jemin",
    }
}
